//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.Import.Console.Resource {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNos.Import.Console.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least on of required files is missing ähnelt.
        /// </summary>
        internal static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} cards parsed ähnelt.
        /// </summary>
        internal static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database has been initialized. ähnelt.
        /// </summary>
        internal static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database may not be up to date. Please consider updating your database. ähnelt.
        /// </summary>
        internal static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parsing done! ähnelt.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} drop items parsed ähnelt.
        /// </summary>
        internal static string DROP_PARSED {
            get {
                return ResourceManager.GetString("DROP_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the directory of files to parse ähnelt.
        /// </summary>
        internal static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} items parsed ähnelt.
        /// </summary>
        internal static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} maps parsed ähnelt.
        /// </summary>
        internal static string MAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MapTypeMaps parsed ähnelt.
        /// </summary>
        internal static string MAPTYPEMAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPEMAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MapTypes parsed ähnelt.
        /// </summary>
        internal static string MAPTYPES_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} monsters parsed ähnelt.
        /// </summary>
        internal static string MONSTERS_PARSED {
            get {
                return ResourceManager.GetString("MONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need a directory tree like this : ähnelt.
        /// </summary>
        internal static string NEED_TREE {
            get {
                return ResourceManager.GetString("NEED_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This item id is not valid! ähnelt.
        /// </summary>
        internal static string NO_ITEM {
            get {
                return ResourceManager.GetString("NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} npc-monsters parsed ähnelt.
        /// </summary>
        internal static string NPCMONSTERS_PARSED {
            get {
                return ResourceManager.GetString("NPCMONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} npcs parsed ähnelt.
        /// </summary>
        internal static string NPCS_PARSED {
            get {
                return ResourceManager.GetString("NPCS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Accounts? ähnelt.
        /// </summary>
        internal static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse ALL? ähnelt.
        /// </summary>
        internal static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Cards? ähnelt.
        /// </summary>
        internal static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Drop? !for MapType dependant drop use MapTypes! ähnelt.
        /// </summary>
        internal static string PARSE_DROP {
            get {
                return ResourceManager.GetString("PARSE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Items? ähnelt.
        /// </summary>
        internal static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse MapNpcs? ähnelt.
        /// </summary>
        internal static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Maps? ähnelt.
        /// </summary>
        internal static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse MapTypes? we suggest using with MapTypeMaps ähnelt.
        /// </summary>
        internal static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse NpcMonsters? ähnelt.
        /// </summary>
        internal static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse NpcMonsterData? ähnelt.
        /// </summary>
        internal static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Npcs? ähnelt.
        /// </summary>
        internal static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Portals? ähnelt.
        /// </summary>
        internal static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Recipes? ähnelt.
        /// </summary>
        internal static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Shopitems? ähnelt.
        /// </summary>
        internal static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Shops? ähnelt.
        /// </summary>
        internal static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Shopskills? ähnelt.
        /// </summary>
        internal static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Skills? ähnelt.
        /// </summary>
        internal static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to parse Teleporters? ähnelt.
        /// </summary>
        internal static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} portals parsed ähnelt.
        /// </summary>
        internal static string PORTALS_PARSED {
            get {
                return ResourceManager.GetString("PORTALS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} recipes parsed ähnelt.
        /// </summary>
        internal static string RECIPES_PARSED {
            get {
                return ResourceManager.GetString("RECIPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RespawnTypes parsed ähnelt.
        /// </summary>
        internal static string RESPAWNTYPE_PARSED {
            get {
                return ResourceManager.GetString("RESPAWNTYPE_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} shopitems parsed ähnelt.
        /// </summary>
        internal static string SHOPITEMS_PARSED {
            get {
                return ResourceManager.GetString("SHOPITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} shops parsed ähnelt.
        /// </summary>
        internal static string SHOPS_PARSED {
            get {
                return ResourceManager.GetString("SHOPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} shopskills parsed ähnelt.
        /// </summary>
        internal static string SHOPSKILLS_PARSED {
            get {
                return ResourceManager.GetString("SHOPSKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} skills parsed ähnelt.
        /// </summary>
        internal static string SKILLS_PARSED {
            get {
                return ResourceManager.GetString("SKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} teleporters parsed ähnelt.
        /// </summary>
        internal static string TELEPORTERS_PARSED {
            get {
                return ResourceManager.GetString("TELEPORTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} timespaces parsed ähnelt.
        /// </summary>
        internal static string TIMESPACES_PARSED {
            get {
                return ResourceManager.GetString("TIMESPACES_PARSED", resourceCulture);
            }
        }
    }
}
