////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("ps_op")]
    public class AddPetSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short PositionPartner { get; set; }

        [PacketIndex(1)]
        public short PositionSkill { get; set; }

        #endregion
    }
}
