// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-beta1-61207")]
    public sealed partial class Aphrodite77 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aphrodite77));
        
        string IMigrationMetadata.Id
        {
            get { return "201712222249579_Aphrodite77"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
