////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("Afk", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class Afkpacket : PacketDefinition
    {
        #region Properties

        public string Data { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Afk";

        public static string ReturnHelp()
        {
            return "$Afk";
        }

        #endregion
    }
}
