////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Backpack", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class BackpackPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Backpack";

        public static string ReturnHelp() => "$Backpack";

        #endregion
    }
}