////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Bank", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class BankPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Mode { get; set; }

        [PacketIndex(1)]
        public string Param1 { get; set; }

        [PacketIndex(2)]
        public long Param2 { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Bank {Mode} {Param1} {Param2}";

        public static string ReturnHelp()
        {

            return "Display Help: $Bank Help\n" +


                   "Display Balance: $Bank Balance\n" +


                   "Deposit Gold: $Bank Deposit AMOUNT\n" +


                   "Withdraw Gold: $Bank Withdraw AMOUNT\n" +


                   "Send Gold: $Bank Send RECEIVER AMOUNT\nn";
        }

        #endregion
    }
}