
////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;
namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Buy", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class BuyPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Item { get; set; }

        [PacketIndex(1)]
        public int Amount { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Buy {Item} {Amount}";

        public static string ReturnHelp()
        {
            return "$Buy ITEM MENGE";
        }

        #endregion
    }
}