////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$FLvl", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeFairyLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short FairyLevel { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$FLvl {FairyLevel}";

        public static string ReturnHelp()
        {
            return "$FLvl FAIRYLEVEL";
        }

        #endregion
    }
}