////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ChangeDignity", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeDignityPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public float Dignity { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$ChangeDignity {Dignity}";

        public static string ReturnHelp()
        {
            return "$ChangeDignity AMOUNT";
        }

        #endregion
    }
}