////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ChannelInfo", PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class ChannelInfoPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$ChannelInfo";

        public static string ReturnHelp()
        {
            return "$ChannelInfo";
        }

        #endregion
    }
}