////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$CharStat", PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class CharacterStatsPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$CharStat {CharacterName}";

        public static string ReturnHelp()
        {
            return "$CharStat CHARACTERNAME";
        }

        #endregion
    }
}