////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ClearMap", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ClearMapPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$ClearMap";

        public static string ReturnHelp()
        {
            return "$ClearMap";
        }

        #endregion
    }
}