////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ClearMail", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class ClearMailPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$ClearMail";

        public static string ReturnHelp()
        {
            return "$ClearMail";
        }

        #endregion
    }
}