////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Clone", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class CloneItemPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Slot { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Clone {Slot}";

        public static string ReturnHelp()
        {
            return "$Clone SLOT";
        }

        #endregion
    }
}