////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Item", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class CreateItemPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short VNum { get; set; }

        [PacketIndex(1)]
        public int? Design { get; set; }

        [PacketIndex(2)]
        public byte? Upgrade { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$CreateItem {VNum} {Design} {Upgrade}";

        public static string ReturnHelp()
        {
            return "$CreateItem ITEMVNUM DESIGN/RARE/AMOUNT/WINGS UPGRADE";
        }

        #endregion

    }
}