////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Demote", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class DemotePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Demote {CharacterName}";

        public static string ReturnHelp()
        {
            return "$Demote CHARACTERNAME";
        }

        #endregion
    }
}