////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Faction", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class FactionPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Faction";

        public static string ReturnHelp()
        {
            return "$Faction";
        }

        #endregion
    }
}