////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$GetDrop", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class GetDropPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$GetDrop";

        public static string ReturnHelp()
        {
            return "$GetDrop";
        }

        #endregion
    }
}