////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$InstanceMusic", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class InstanceMusicPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Music { get; set; }

        [PacketIndex(1)]
        public string Maps { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$InstanceMusic {Music} {Maps}";

        public static string ReturnHelp()
        {
            return "$InstanceMusic (?)MUSIC (*)nullable";
        }

        #endregion
    }
}