////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Invisible", PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class InvisiblePacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Invisible";

        public static string ReturnHelp()
        {
            return "$Invisible";
        }

        #endregion
    }
}