////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Kill", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class KillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Kill {CharacterName}";

        public static string ReturnHelp()
        {
            return "$Kill CHARACTERNAME";
        }

        #endregion
    }
}