////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$MapDance", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class MapDancePacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$MapDance";

        public static string ReturnHelp()
        {
            return "$MapDance";
        }

        #endregion
    }
}