////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Mute", PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class MutePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1)]
        public int Duration { get; set; }

        [PacketIndex(2, SerializeToEnd = true)]
        public string Reason { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Mute {CharacterName} {Duration} {Reason}";

        public static string ReturnHelp()
        {
            return "$Mute CHARACTERNAME DURATION(MINUTES) REASON";
        }

        #endregion
    }
}