////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Position", PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class PositionPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Position";

        public static string ReturnHelp()
        {
            return "$Position";
        }

        #endregion
    }
}