////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$RemoveNpcMonster", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class RemoveNpcMonsterPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$RemoveNpcMonster";

        public static string ReturnHelp()
        {
            return "$RemoveNpcMonster";
        }

        #endregion
    }
}