////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$RestartAll", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class RestartAllPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string WorldGroup { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$RestartAll {WorldGroup}";

        public static string ReturnHelp()
        {
            return "$RestartAll WORLDGROUP(*)";
        }

        #endregion
    }
}