////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Restart", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class RestartPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Restart";

        public static string ReturnHelp()
        {
            return "$Restart";
        }

        #endregion
    }
}