////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Shutdown", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class ShutdownPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Shutdown";

        public static string ReturnHelp()
        {
            return "$Shutdown";
        }

        #endregion
    }
}