////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Sudo", PassNonParseablePacket = true, Authority = AuthorityType.Admin)]
    public class SudoPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string CommandContents { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Sudo {CharacterName} {CommandContents}";

        public static string ReturnHelp()
        {
            return "$Sudo CHARACTERNAME COMMANDCONTENTS";
        }

        #endregion
    }
}