////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Teleport", "$Tp", "$TP" , PassNonParseablePacket = true, Authority = AuthorityType.Supporter)]
    public class TeleportPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Data { get; set; }

        [PacketIndex(1)]
        public short X { get; set; }

        [PacketIndex(2)]
        public short Y { get; set; }

        #endregion

        #region Methods

        public override string ToString() => $"$Teleport {Data} {X} {Y}";

        public static string ReturnHelp()
        {
            return "$Teleport CHARACTERNAME/MAP X(?) Y(?)";
        }

        #endregion
    }
}