////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Undercover", "$UC", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class UndercoverPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"$Undercover";

        public static string ReturnHelp()
        {
            return "$Undercover\n$UC";
        }

        #endregion
    }
}